CREATE USER commute IDENTIFIED BY Welcome1;
GRANT create session TO commute;
GRANT create table TO commute;
GRANT create view TO commute;
GRANT create any trigger TO commute;
GRANT create any procedure TO commute;
GRANT create sequence TO commute;
GRANT create synonym TO commute;
GRANT UNLIMITED TABLESPACE TO commute;
commit;
